Seperated terraform variables for min/max nodes
jenkins-x/terraform-google-jx pull request #229
Opened 2023-03-28 11:53 UTC by mmn0o7

Seperated terraform variables for min/max nodes because the node pool and the cluster used same variables previously, changing the node pool would change the cluster initial node count causing the recreation of the cluster.

initial_cluster_node_count = var.initial_cluster_node_count
initial_primary_node_pool_node_count = var.initial_primary_node_pool_node_count
autoscaler_min_node_count    = var.autoscaler_min_node_count
autoscaler_max_node_count    = var.autoscaler_max_node_count

2023-03-28 12:38 UTC, tomhobson requested changes

2023-03-28 12:38 UTC, tomhobson commented on modules/cluster/variables.tf
> +
you've got some additional whitespace here

2023-03-28 12:38 UTC, tomhobson commented on modules/cluster/variables.tf
> +  default     = "ANY"
Is this the right syntax? a number with a string as default?

2023-03-29 06:39 UTC, mmn0o7 commented
Updated variable descriptions, removed whitespaces and fixed type
@tomhobson

2023-03-29 08:13 UTC, tomhobson approved these changes

2023-03-30 14:02 UTC, tomhobson commented
/ok-to-test

2023-03-30 14:04 UTC, merged